// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	auth2 "chatapp/backend/auth"
	"chatapp/backend/chats/controller"
	"chatapp/backend/chats/repo"
	"chatapp/backend/chats/service"
	"chatapp/backend/di"
	"chatapp/backend/ent"
	controller4 "chatapp/backend/login/controller"
	repo3 "chatapp/backend/login/repo"
	service4 "chatapp/backend/login/service"
	controller3 "chatapp/backend/messages/controller"
	"chatapp/backend/messages/hub"
	repo4 "chatapp/backend/messages/repo"
	service3 "chatapp/backend/messages/service"
	controller2 "chatapp/backend/users/controller"
	repo2 "chatapp/backend/users/repo"
	service2 "chatapp/backend/users/service"
	"context"
	"firebase.google.com/go/v4/auth"
	"github.com/gin-gonic/gin"
)

// Injectors from di.go:

func InitializeDI(context2 context.Context, router *gin.Engine, db *ent.Client, auth3 *auth.Client) di.Controllers {
	chatRepoImpl := repo.NewChatRepo(db, context2)
	userRepoImpl := repo2.NewUserRepo(context2, db)
	chatServiceImpl := service.NewChatService(chatRepoImpl, userRepoImpl)
	authService := auth2.NewAuthService(auth3, context2)
	loginRepoImpl := repo3.NewLoginRepo(context2, db)
	userServiceImpl := service2.NewUserService(userRepoImpl, loginRepoImpl, authService)
	chatControllerImpl := controller.NewChatController(router, chatServiceImpl, authService, userServiceImpl)
	userControllerImpl := controller2.NewUserController(router, userServiceImpl, authService)
	messageRepoImpl := repo4.NewMessageRepo(context2, db)
	messageServiceImpl := service3.NewMessageService(messageRepoImpl, chatRepoImpl, userRepoImpl)
	hubHub := hub.NewHub(userServiceImpl, messageServiceImpl)
	messageControllerImpl := controller3.NewMessageController(router, messageServiceImpl, authService, hubHub, userServiceImpl)
	loginServiceImpl := service4.NewLoginService(loginRepoImpl, authService)
	loginControllerImpl := controller4.NewLoginController(router, loginServiceImpl)
	controllers := di.NewControllers(chatControllerImpl, userControllerImpl, messageControllerImpl, loginControllerImpl, hubHub)
	return controllers
}
