// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatapp/backend/ent/chat"
	"chatapp/backend/ent/chatroles"
	"chatapp/backend/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRolesCreate is the builder for creating a ChatRoles entity.
type ChatRolesCreate struct {
	config
	mutation *ChatRolesMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (crc *ChatRolesCreate) SetRole(c chatroles.Role) *ChatRolesCreate {
	crc.mutation.SetRole(c)
	return crc
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (crc *ChatRolesCreate) SetChatID(id int) *ChatRolesCreate {
	crc.mutation.SetChatID(id)
	return crc
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (crc *ChatRolesCreate) SetNillableChatID(id *int) *ChatRolesCreate {
	if id != nil {
		crc = crc.SetChatID(*id)
	}
	return crc
}

// SetChat sets the "chat" edge to the Chat entity.
func (crc *ChatRolesCreate) SetChat(c *Chat) *ChatRolesCreate {
	return crc.SetChatID(c.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (crc *ChatRolesCreate) SetUserID(id int) *ChatRolesCreate {
	crc.mutation.SetUserID(id)
	return crc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (crc *ChatRolesCreate) SetNillableUserID(id *int) *ChatRolesCreate {
	if id != nil {
		crc = crc.SetUserID(*id)
	}
	return crc
}

// SetUser sets the "user" edge to the User entity.
func (crc *ChatRolesCreate) SetUser(u *User) *ChatRolesCreate {
	return crc.SetUserID(u.ID)
}

// Mutation returns the ChatRolesMutation object of the builder.
func (crc *ChatRolesCreate) Mutation() *ChatRolesMutation {
	return crc.mutation
}

// Save creates the ChatRoles in the database.
func (crc *ChatRolesCreate) Save(ctx context.Context) (*ChatRoles, error) {
	var (
		err  error
		node *ChatRoles
	)
	if len(crc.hooks) == 0 {
		if err = crc.check(); err != nil {
			return nil, err
		}
		node, err = crc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatRolesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = crc.check(); err != nil {
				return nil, err
			}
			crc.mutation = mutation
			if node, err = crc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(crc.hooks) - 1; i >= 0; i-- {
			if crc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = crc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, crc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ChatRoles)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ChatRolesMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (crc *ChatRolesCreate) SaveX(ctx context.Context) *ChatRoles {
	v, err := crc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crc *ChatRolesCreate) Exec(ctx context.Context) error {
	_, err := crc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crc *ChatRolesCreate) ExecX(ctx context.Context) {
	if err := crc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (crc *ChatRolesCreate) check() error {
	if _, ok := crc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChatRoles.role"`)}
	}
	if v, ok := crc.mutation.Role(); ok {
		if err := chatroles.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatRoles.role": %w`, err)}
		}
	}
	return nil
}

func (crc *ChatRolesCreate) sqlSave(ctx context.Context) (*ChatRoles, error) {
	_node, _spec := crc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (crc *ChatRolesCreate) createSpec() (*ChatRoles, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatRoles{config: crc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: chatroles.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chatroles.FieldID,
			},
		}
	)
	if value, ok := crc.mutation.Role(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: chatroles.FieldRole,
		})
		_node.Role = value
	}
	if nodes := crc.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.ChatTable,
			Columns: []string{chatroles.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chat_chat_roles = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.UserTable,
			Columns: []string{chatroles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_roles_in_chats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatRolesCreateBulk is the builder for creating many ChatRoles entities in bulk.
type ChatRolesCreateBulk struct {
	config
	builders []*ChatRolesCreate
}

// Save creates the ChatRoles entities in the database.
func (crcb *ChatRolesCreateBulk) Save(ctx context.Context) ([]*ChatRoles, error) {
	specs := make([]*sqlgraph.CreateSpec, len(crcb.builders))
	nodes := make([]*ChatRoles, len(crcb.builders))
	mutators := make([]Mutator, len(crcb.builders))
	for i := range crcb.builders {
		func(i int, root context.Context) {
			builder := crcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatRolesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crcb *ChatRolesCreateBulk) SaveX(ctx context.Context) []*ChatRoles {
	v, err := crcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crcb *ChatRolesCreateBulk) Exec(ctx context.Context) error {
	_, err := crcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crcb *ChatRolesCreateBulk) ExecX(ctx context.Context) {
	if err := crcb.Exec(ctx); err != nil {
		panic(err)
	}
}
