// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatapp/backend/ent/chat"
	"chatapp/backend/ent/chatroles"
	"chatapp/backend/ent/predicate"
	"chatapp/backend/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRolesUpdate is the builder for updating ChatRoles entities.
type ChatRolesUpdate struct {
	config
	hooks    []Hook
	mutation *ChatRolesMutation
}

// Where appends a list predicates to the ChatRolesUpdate builder.
func (cru *ChatRolesUpdate) Where(ps ...predicate.ChatRoles) *ChatRolesUpdate {
	cru.mutation.Where(ps...)
	return cru
}

// SetRole sets the "role" field.
func (cru *ChatRolesUpdate) SetRole(c chatroles.Role) *ChatRolesUpdate {
	cru.mutation.SetRole(c)
	return cru
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (cru *ChatRolesUpdate) SetChatID(id int) *ChatRolesUpdate {
	cru.mutation.SetChatID(id)
	return cru
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (cru *ChatRolesUpdate) SetNillableChatID(id *int) *ChatRolesUpdate {
	if id != nil {
		cru = cru.SetChatID(*id)
	}
	return cru
}

// SetChat sets the "chat" edge to the Chat entity.
func (cru *ChatRolesUpdate) SetChat(c *Chat) *ChatRolesUpdate {
	return cru.SetChatID(c.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cru *ChatRolesUpdate) SetUserID(id int) *ChatRolesUpdate {
	cru.mutation.SetUserID(id)
	return cru
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cru *ChatRolesUpdate) SetNillableUserID(id *int) *ChatRolesUpdate {
	if id != nil {
		cru = cru.SetUserID(*id)
	}
	return cru
}

// SetUser sets the "user" edge to the User entity.
func (cru *ChatRolesUpdate) SetUser(u *User) *ChatRolesUpdate {
	return cru.SetUserID(u.ID)
}

// Mutation returns the ChatRolesMutation object of the builder.
func (cru *ChatRolesUpdate) Mutation() *ChatRolesMutation {
	return cru.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (cru *ChatRolesUpdate) ClearChat() *ChatRolesUpdate {
	cru.mutation.ClearChat()
	return cru
}

// ClearUser clears the "user" edge to the User entity.
func (cru *ChatRolesUpdate) ClearUser() *ChatRolesUpdate {
	cru.mutation.ClearUser()
	return cru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cru *ChatRolesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cru.hooks) == 0 {
		if err = cru.check(); err != nil {
			return 0, err
		}
		affected, err = cru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatRolesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cru.check(); err != nil {
				return 0, err
			}
			cru.mutation = mutation
			affected, err = cru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cru.hooks) - 1; i >= 0; i-- {
			if cru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cru *ChatRolesUpdate) SaveX(ctx context.Context) int {
	affected, err := cru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cru *ChatRolesUpdate) Exec(ctx context.Context) error {
	_, err := cru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cru *ChatRolesUpdate) ExecX(ctx context.Context) {
	if err := cru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cru *ChatRolesUpdate) check() error {
	if v, ok := cru.mutation.Role(); ok {
		if err := chatroles.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatRoles.role": %w`, err)}
		}
	}
	return nil
}

func (cru *ChatRolesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chatroles.Table,
			Columns: chatroles.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chatroles.FieldID,
			},
		},
	}
	if ps := cru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cru.mutation.Role(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: chatroles.FieldRole,
		})
	}
	if cru.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.ChatTable,
			Columns: []string{chatroles.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.ChatTable,
			Columns: []string{chatroles.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.UserTable,
			Columns: []string{chatroles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.UserTable,
			Columns: []string{chatroles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ChatRolesUpdateOne is the builder for updating a single ChatRoles entity.
type ChatRolesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatRolesMutation
}

// SetRole sets the "role" field.
func (cruo *ChatRolesUpdateOne) SetRole(c chatroles.Role) *ChatRolesUpdateOne {
	cruo.mutation.SetRole(c)
	return cruo
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (cruo *ChatRolesUpdateOne) SetChatID(id int) *ChatRolesUpdateOne {
	cruo.mutation.SetChatID(id)
	return cruo
}

// SetNillableChatID sets the "chat" edge to the Chat entity by ID if the given value is not nil.
func (cruo *ChatRolesUpdateOne) SetNillableChatID(id *int) *ChatRolesUpdateOne {
	if id != nil {
		cruo = cruo.SetChatID(*id)
	}
	return cruo
}

// SetChat sets the "chat" edge to the Chat entity.
func (cruo *ChatRolesUpdateOne) SetChat(c *Chat) *ChatRolesUpdateOne {
	return cruo.SetChatID(c.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cruo *ChatRolesUpdateOne) SetUserID(id int) *ChatRolesUpdateOne {
	cruo.mutation.SetUserID(id)
	return cruo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cruo *ChatRolesUpdateOne) SetNillableUserID(id *int) *ChatRolesUpdateOne {
	if id != nil {
		cruo = cruo.SetUserID(*id)
	}
	return cruo
}

// SetUser sets the "user" edge to the User entity.
func (cruo *ChatRolesUpdateOne) SetUser(u *User) *ChatRolesUpdateOne {
	return cruo.SetUserID(u.ID)
}

// Mutation returns the ChatRolesMutation object of the builder.
func (cruo *ChatRolesUpdateOne) Mutation() *ChatRolesMutation {
	return cruo.mutation
}

// ClearChat clears the "chat" edge to the Chat entity.
func (cruo *ChatRolesUpdateOne) ClearChat() *ChatRolesUpdateOne {
	cruo.mutation.ClearChat()
	return cruo
}

// ClearUser clears the "user" edge to the User entity.
func (cruo *ChatRolesUpdateOne) ClearUser() *ChatRolesUpdateOne {
	cruo.mutation.ClearUser()
	return cruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cruo *ChatRolesUpdateOne) Select(field string, fields ...string) *ChatRolesUpdateOne {
	cruo.fields = append([]string{field}, fields...)
	return cruo
}

// Save executes the query and returns the updated ChatRoles entity.
func (cruo *ChatRolesUpdateOne) Save(ctx context.Context) (*ChatRoles, error) {
	var (
		err  error
		node *ChatRoles
	)
	if len(cruo.hooks) == 0 {
		if err = cruo.check(); err != nil {
			return nil, err
		}
		node, err = cruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChatRolesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cruo.check(); err != nil {
				return nil, err
			}
			cruo.mutation = mutation
			node, err = cruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cruo.hooks) - 1; i >= 0; i-- {
			if cruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ChatRoles)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ChatRolesMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cruo *ChatRolesUpdateOne) SaveX(ctx context.Context) *ChatRoles {
	node, err := cruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cruo *ChatRolesUpdateOne) Exec(ctx context.Context) error {
	_, err := cruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cruo *ChatRolesUpdateOne) ExecX(ctx context.Context) {
	if err := cruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cruo *ChatRolesUpdateOne) check() error {
	if v, ok := cruo.mutation.Role(); ok {
		if err := chatroles.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatRoles.role": %w`, err)}
		}
	}
	return nil
}

func (cruo *ChatRolesUpdateOne) sqlSave(ctx context.Context) (_node *ChatRoles, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chatroles.Table,
			Columns: chatroles.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: chatroles.FieldID,
			},
		},
	}
	id, ok := cruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatRoles.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatroles.FieldID)
		for _, f := range fields {
			if !chatroles.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatroles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cruo.mutation.Role(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: chatroles.FieldRole,
		})
	}
	if cruo.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.ChatTable,
			Columns: []string{chatroles.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.ChatTable,
			Columns: []string{chatroles.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: chat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.UserTable,
			Columns: []string{chatroles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroles.UserTable,
			Columns: []string{chatroles.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatRoles{config: cruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
