// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatapp/backend/ent/login"
	"chatapp/backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Login is the model entity for the Login schema.
type Login struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// UID holds the value of the "uid" field.
	UID string `json:"uid,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Status holds the value of the "status" field.
	Status login.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginQuery when eager-loading is set.
	Edges LoginEdges `json:"edges"`
}

// LoginEdges holds the relations/edges for other nodes in the graph.
type LoginEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Login) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case login.FieldID:
			values[i] = new(sql.NullInt64)
		case login.FieldUsername, login.FieldEmail, login.FieldUID, login.FieldStatus:
			values[i] = new(sql.NullString)
		case login.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Login", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Login fields.
func (l *Login) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case login.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case login.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				l.Username = value.String
			}
		case login.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				l.Email = value.String
			}
		case login.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				l.UID = value.String
			}
		case login.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				l.CreatedAt = value.Time
			}
		case login.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				l.Status = login.Status(value.String)
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Login entity.
func (l *Login) QueryUser() *UserQuery {
	return (&LoginClient{config: l.config}).QueryUser(l)
}

// Update returns a builder for updating this Login.
// Note that you need to call Login.Unwrap() before calling this method if this Login
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Login) Update() *LoginUpdateOne {
	return (&LoginClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Login entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Login) Unwrap() *Login {
	_tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Login is not a transactional entity")
	}
	l.config.driver = _tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Login) String() string {
	var builder strings.Builder
	builder.WriteString("Login(")
	builder.WriteString(fmt.Sprintf("id=%v, ", l.ID))
	builder.WriteString("username=")
	builder.WriteString(l.Username)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(l.Email)
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(l.UID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(l.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", l.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Logins is a parsable slice of Login.
type Logins []*Login

func (l Logins) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
